language: r
cache: packages

r_github_packages:
  - r-lib/pkgdown

before_script:
  - Rscript -e "Sys.setenv(userid = '$ETN_USER')"
  - Rscript -e "Sys.setenv(pwd = '$ETN_PASSWORD')"

after_success:
  - Rscript -e "pkgdown::build_site(preview = FALSE)"

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
