SELECT 
    detections.receiver,
    detections.transmitter,
    detections.transmitter_name,
    detections.transmitter_serial,
    detections.sensor_value,
    detections.sensor_unit,
    detections.sensor2_value,
    detections.sensor2_unit,
    detections.station_name,
    detections.datetime,
    detections.id_pk,
    detections.qc_flag,
    detections.file,
    detections.latitude,
    detections.longitude,
    detections.deployment_fk,
    detections.signal_to_noise_ratio,
    detections.detection_file_id,
    tags.type as tag_type,
    tags.model as tag_model,
    tags.tag_code_space,
    tags.owner_pi as tag_owner_pi,
    tags.owner_organization as tag_owner_organization,
    tags.min_delay as tag_min_delay,
    tags.max_delay as tag_max_delay,
    tags.frequency as tag_frequency,
    tags.acoustic_tag_type,
    tags.sensor_type AS tag_sensor_type,
    tags.intercept AS tag_intercept,
    tags.slope AS tag_slope,
        CASE
            WHEN ((tags.sensor_type)::text = 'P'::text) THEN ((tags.intercept)::double precision + (detections.sensor_value * (tags.slope)::double precision))
            ELSE NULL::double precision
        END AS sensor_value_depth_meters,
    animals.person_id,
    animals.animal_id,
    animals.scientific_name,
    animals.common_name,
    animals.length,
    animals.length_type,
    animals.length_units,
    animals.length2,
    animals.length2_type,
    animals.length2_units,
    animals.weight_units,
    animals.age,
    animals.age_units,
    animals.sex,
    animals.life_stage,
    animals.capture_location,
    animals.capture_depth,
    animals.utc_release_date_time,
    animals.comments,
    animals.est_tag_life,
    animals.wild_or_hatchery,
    animals.stock,
    animals.dna_sample_taken,
    animals.treatment_type,
    animals.dissolved_oxygen,
    animals.sedative,
    animals.sedative_concentration,
    animals.temperature_change,
    animals.holding_temperature,
    animals.preop_holding_period,
    animals.post_op_holding_period,
    animals.surgery_location,
    animals.date_of_surgery,
    animals.anaesthetic,
    animals.buffer,
    animals.anaesthetic_concentration,
    animals.buffer_concentration_in_anaesthetic,
    animals.anesthetic_concentration_in_recirculation,
    animals.buffer_concentration_in_recirculation,
    animals.id_pk,
    animals.catched_date_time,
    animals.tag_fk,
    animals.capture_latitude,
    animals.capture_longitude,
    animals.release_latitude,
    animals.release_longitude,
    animals.surgery_latitude,
    animals.surgery_longitude,
    animals.recapture_date,
    animals.implant_type,
    animals.implant_method,
    animals.date_modified,
    animals.date_created,
    animals.release_location,
    animals.length3,
    animals.length3_type,
    animals.length3_units,
    animals.length4,
    animals.length4_type,
    animals.length4_units,
    animals.weight,
    animals.end_date_tag,
    animals.capture_method,
    animals.project_fk,
    animal_project.project AS animal_project,
    animal_project.name AS animal_project_name,
    animal_project.projectcode AS animal_project_code,
    animal_project.moratorium AS animal_moratorium,
    network_project.project AS network_project,
    network_project.name AS network_project_name,
    network_project.projectcode AS network_project_code,
    network_project.moratorium AS network_moratorium,
    deployments.station_name AS deployment_station_name,
    deployments.deploy_date_time as deployment_deploy_date_time,
    deployments.location_name AS deployment_location,
    deployments.location_manager AS deployment_location_manager, 
    deployments.location_description as deployment_location_description,
    deployments.deploy_lat AS deployment_deploy_lat,
    deployments.deploy_long as deployment_deploy_long,
    deployments.recover_lat AS deployment_recoverr_lat,
    deployments.recover_long AS deployment_recover_long,
    deployments.intended_lat AS deployment_intended_lat,
    deployments.intended_long as deployment_intended_long,
    deployments.bottom_depth AS deployment_bottom_depth,
    deployments.riser_length AS deployment_riser_length,
    deployments.instrument_depth AS deployment_instrument_depth,
    receivers.serial_number AS receiver_serial_number,
    receivers.model_number AS receiver_model_number,
    receivers.owner_organization AS receiver_owner_organization,
    receivers.status AS receiver_status,
    receivers.receiver_type AS receiver_receiver_type,
    receivers.manufacturer_fk AS receiver_manufacturer_fk
  FROM vliz.detections_view AS detections
    JOIN vliz.tags ON ((detections.transmitter)::text = (tags.tag_code_space)::text)
    JOIN vliz.animal_tag_release ON (animal_tag_release.tag_fk = tags.id_pk)
    JOIN vliz.animals_view animals ON (animals.id_pk = animal_tag_release.animal_fk)
    JOIN vliz.projects animal_project ON (animal_project.id = animals.project_fk)
    JOIN vliz.deployments_view as deployments ON (deployments.id_pk = detections.deployment_fk)
    JOIN vliz.projects network_project ON (network_project.id = deployments.project_fk)
    JOIN vliz.receivers ON (receivers.id_pk = deployments.receiver_fk);
