---
title: "Package Options"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Package Options}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The package has a number of options that can be set via [System Environmental variables](https://stat.ethz.ch/R-manual/R-devel/library/base/html/EnvVar.html). You usually don't need to change these options, and most of them are actually there to help contributors in developing the package.

## How to change these options.

You can change a System Environmental Variable from within R with ?Sys.setenv() and get a set value with ?Sys.getenv(). To set variables more permanently you can use the `.Renviron` file, which can be easily changed with ?usethis::edit_r_environ().

## Options overview

The following options are available:

### Login credentials
See [Set Up Your ETN Username and Password](etn_credentials.html). These variables allow you to set your etn database username and password.

- `ETN_USER` : Username to the etn database
- `ETN_PWD` : Password to the etn database

### API Options
- `ETN_PROTOCOL` : The package automatically switches between using a local connection to the etn database or the OpenCPU API depending on the availability of a local database connection is available. You can force the package to always use one or the other by setting this option to `opencpu` or `localdb`.
- `ETN_TEST_API` : **DANGER** Overwrite the url where the etn OpenCPU API is hosted. This variable is used to switch the entire package over to a different url, for example the testing api. Changing this variable to anything other than the testing api url will break the package. 


